//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lock_Management_Pro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lock_ProDBEntities : DbContext
    {
        public Lock_ProDBEntities()
            : base("name=Lock_ProDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ProSerial> tbl_ProSerial { get; set; }
        public virtual DbSet<tbl_Software> tbl_Software { get; set; }
        public virtual DbSet<tbl_LockList> tbl_LockList { get; set; }
    }
}
