//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lock_Management_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Software
    {
        public int ID { get; set; }
        public string ProName { get; set; }
        public Nullable<int> Fix_num1 { get; set; }
        public Nullable<int> Fix_num2 { get; set; }
    }
}
