//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lock_Management_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LockList
    {
        public int ID { get; set; }
        public string cu_name { get; set; }
        public string cu_mobile { get; set; }
        public string serial_num { get; set; }
        public Nullable<int> identity_num { get; set; }
        public string lock_num { get; set; }
        public Nullable<int> fix_num1 { get; set; }
        public Nullable<int> fix_num2 { get; set; }
        public string lock_date { get; set; }
        public Nullable<int> lock_count { get; set; }
    }
}
